import { Fatwa, NewsItem } from '../types';
import { StorageService } from './storage';

// In-flight promise cache to avoid duplicate API calls
const inFlightTranslations = new Map<string, Promise<any>>();

export interface TranslationResult {
  titleEn: string;
  questionEn?: string;
  answerEn?: string;
  contentEn?: string;
  titleAr: string;
  questionAr?: string;
  answerAr?: string;
  contentAr?: string;
}

export const isEnglishTranslationMissingOrFallback = (fatwa: Fatwa): boolean => {
  const enAnswer = fatwa.answer?.en?.trim() || '';
  const urAnswer = fatwa.answer?.ur?.trim() || '';
  
  // Missing if empty or exact duplicate of Urdu text
  if (!enAnswer) return true;
  if (enAnswer === urAnswer) return true;
  
  // If english answer is too short compared to urdu while urdu has real text
  if (urAnswer.length > 50 && enAnswer.length < 15 && !fatwa.title?.en) {
    return true;
  }

  return false;
};

export const isArabicTranslationMissingOrFallback = (fatwa: Fatwa): boolean => {
  const arAnswer = fatwa.answer?.ar?.trim() || '';
  const urAnswer = fatwa.answer?.ur?.trim() || '';
  if (!arAnswer) return true;
  if (arAnswer === urAnswer) return true;
  return false;
};

export const translateFatwaServerSide = async (
  titleUr: string,
  questionUr: string,
  answerUr: string
): Promise<TranslationResult> => {
  const settings = StorageService.getSiteSettings();
  const response = await fetch('/api/translate-fatwa', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contentType: 'fatwa',
      titleUr: titleUr || '',
      questionUr: questionUr || '',
      answerUr: answerUr || '',
      geminiApiKey: settings?.geminiApiKey || undefined,
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    throw new Error(errData.error || `Translation request failed with status ${response.status}`);
  }

  const result = await response.json();
  if (!result.success || !result.data) {
    throw new Error(result.error || 'Failed to obtain translation from Gemini API.');
  }

  return {
    titleEn: result.data.titleEn || titleUr,
    questionEn: result.data.questionEn || questionUr,
    answerEn: result.data.answerEn || answerUr,
    titleAr: result.data.titleAr || titleUr,
    questionAr: result.data.questionAr || questionUr,
    answerAr: result.data.answerAr || answerUr,
  };
};

export const translateArticleServerSide = async (
  titleUr: string,
  contentUr: string
): Promise<TranslationResult> => {
  const settings = StorageService.getSiteSettings();
  const response = await fetch('/api/translate-content', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contentType: 'article',
      titleUr: titleUr || '',
      contentUr: contentUr || '',
      geminiApiKey: settings?.geminiApiKey || undefined,
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    throw new Error(errData.error || `Translation request failed with status ${response.status}`);
  }

  const result = await response.json();
  if (!result.success || !result.data) {
    throw new Error(result.error || 'Failed to obtain translation from Gemini API.');
  }

  return {
    titleEn: result.data.titleEn || titleUr,
    contentEn: result.data.contentEn || contentUr,
    titleAr: result.data.titleAr || titleUr,
    contentAr: result.data.contentAr || contentUr,
  };
};

export const generateDraftTranslationForFatwa = async (fatwa: Fatwa): Promise<Fatwa> => {
  const cacheKey = `fatwa-trans-${fatwa.id}`;
  if (inFlightTranslations.has(cacheKey)) {
    return inFlightTranslations.get(cacheKey)!;
  }

  const promise = (async () => {
    try {
      const res = await translateFatwaServerSide(
        fatwa.title?.ur || '',
        fatwa.question?.ur || '',
        fatwa.answer?.ur || ''
      );

      const updated: Fatwa = {
        ...fatwa,
        title: {
          ur: fatwa.title?.ur || '',
          ar: res.titleAr || fatwa.title?.ar || fatwa.title?.ur || '',
          en: res.titleEn || fatwa.title?.en || fatwa.title?.ur || '',
        },
        question: {
          ur: fatwa.question?.ur || '',
          ar: res.questionAr || fatwa.question?.ar || fatwa.question?.ur || '',
          en: res.questionEn || fatwa.question?.en || fatwa.question?.ur || '',
        },
        answer: {
          ur: fatwa.answer?.ur || '',
          ar: res.answerAr || fatwa.answer?.ar || fatwa.answer?.ur || '',
          en: res.answerEn || fatwa.answer?.en || fatwa.answer?.ur || '',
        },
        isAiTranslatedEn: true,
        // STRICT RULE: Translations generated by AI remain unapproved drafts until an authorized scholar approves
        isTranslationApproved: false,
        aiTranslatedEnAt: new Date().toISOString(),
      };

      StorageService.updateFatwa(updated);
      return updated;
    } finally {
      inFlightTranslations.delete(cacheKey);
    }
  })();

  inFlightTranslations.set(cacheKey, promise);
  return promise;
};

// Backwards-compatible alias for existing components
export const getOrTranslateFatwaEnglish = async (
  fatwa: Fatwa,
  _forceRefresh = false
): Promise<Fatwa> => {
  return generateDraftTranslationForFatwa(fatwa);
};

export const generateDraftTranslationForNews = async (news: NewsItem): Promise<NewsItem> => {
  const cacheKey = `news-trans-${news.id}`;
  if (inFlightTranslations.has(cacheKey)) {
    return inFlightTranslations.get(cacheKey)!;
  }

  const promise = (async () => {
    try {
      const res = await translateArticleServerSide(
        news.title?.ur || '',
        news.content?.ur || ''
      );

      const updated: NewsItem = {
        ...news,
        title: {
          ur: news.title?.ur || '',
          ar: res.titleAr || news.title?.ar || news.title?.ur || '',
          en: res.titleEn || news.title?.en || news.title?.ur || '',
        },
        content: {
          ur: news.content?.ur || '',
          ar: res.contentAr || news.content?.ar || news.content?.ur || '',
          en: res.contentEn || news.content?.en || news.content?.ur || '',
        },
        isAiTranslated: true,
        isTranslationApproved: false,
      };

      StorageService.updateNews(updated);
      return updated;
    } finally {
      inFlightTranslations.delete(cacheKey);
    }
  })();

  inFlightTranslations.set(cacheKey, promise);
  return promise;
};

export const approveFatwaTranslation = (
  fatwaId: string, 
  approvedBy = 'دارالافتاء جامعہ اسلامیہ',
  customEdits?: Partial<Fatwa>
): Fatwa | null => {
  const fatwas = StorageService.getFatwas();
  const target = fatwas.find(f => f.id === fatwaId);
  if (!target) return null;

  const updated: Fatwa = {
    ...target,
    ...(customEdits || {}),
    isTranslationApproved: true,
    translationApprovedBy: approvedBy,
  };

  StorageService.updateFatwa(updated);
  return updated;
};

export const revokeFatwaTranslationApproval = (fatwaId: string): Fatwa | null => {
  const fatwas = StorageService.getFatwas();
  const target = fatwas.find(f => f.id === fatwaId);
  if (!target) return null;

  const updated: Fatwa = {
    ...target,
    isTranslationApproved: false,
    translationApprovedBy: undefined,
  };

  StorageService.updateFatwa(updated);
  return updated;
};

export const approveNewsTranslation = (
  newsId: string,
  approvedBy = 'ادارہ جامعہ اسلامیہ',
  customEdits?: Partial<NewsItem>
): NewsItem | null => {
  const newsList = StorageService.getNews();
  const target = newsList.find(n => n.id === newsId);
  if (!target) return null;

  const updated: NewsItem = {
    ...target,
    ...(customEdits || {}),
    isTranslationApproved: true,
    translationApprovedBy: approvedBy,
  };

  StorageService.updateNews(updated);
  return updated;
};

export const revokeNewsTranslationApproval = (newsId: string): NewsItem | null => {
  const newsList = StorageService.getNews();
  const target = newsList.find(n => n.id === newsId);
  if (!target) return null;

  const updated: NewsItem = {
    ...target,
    isTranslationApproved: false,
    translationApprovedBy: undefined,
  };

  StorageService.updateNews(updated);
  return updated;
};

